/**
 * Client-side character manifest types + fetcher.
 * The manifest itself is generated by backend Node.js code
 * (vite-plugins/character-manifest.ts) — the browser never reads the filesystem.
 */

export interface CharacterManifestAsset {
  fileName: string;
  /** Relative to the app base path (prepend import.meta.env.BASE_URL). */
  publicUrl: string;
  width: number;
  height: number;
}

export interface CharacterManifestEntry {
  id: string;
  displayName: string;
  folderName: string;
  directions: 4 | 8;
  movements: Record<string, CharacterManifestAsset[]>;
  warnings: string[];
}

export interface CharacterManifestError {
  code: string;
  message: string;
  characterId?: string;
  paths?: string[];
}

export interface CharacterManifest {
  generatedAt: string;
  characters: CharacterManifestEntry[];
  errors: CharacterManifestError[];
  warnings: string[];
}

export function manifestUrl(): string {
  const base = import.meta.env.BASE_URL || '/';
  return `${base}${base.endsWith('/') ? '' : '/'}assets/characters/manifest.json`;
}

export function assetUrl(asset: CharacterManifestAsset): string {
  const base = import.meta.env.BASE_URL || '/';
  return `${base}${base.endsWith('/') ? '' : '/'}${asset.publicUrl}`;
}

export async function fetchCharacterManifest(): Promise<CharacterManifest> {
  const res = await fetch(manifestUrl(), { cache: 'no-store' });
  if (!res.ok) {
    throw new Error(`Failed to load character manifest (HTTP ${res.status})`);
  }
  const data = (await res.json()) as CharacterManifest;
  if (!data || !Array.isArray(data.characters)) {
    throw new Error('Character manifest has an invalid format');
  }
  return data;
}
