/**
 * /admin/characters — professional character editor.
 *
 * Characters are auto-discovered from public/assets/characters via the
 * manifest generated by backend Node code (vite-plugins/character-manifest.ts).
 * The editor edits a CharacterConfigV1 working copy: origin + collision body
 * (auto-saved on commit, like the old editor) and per-frame hurt/hitboxes
 * (explicit "Salvar" with strict validation).
 */
import { useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, ArrowLeft, Circle, Copy, Crosshair, Save, Swords } from 'lucide-react';
import {
  EMPTY_FRAME_CONFIG,
  directionRowsFor,
  detectGrid,
  validateCharacterConfig,
  type CharacterConfigV1,
  type CombatFrameConfig,
  type Direction8,
  type LocalRectangle,
} from '../../../shared/combat/CharacterCombatShapes';
import {
  fetchCharacterManifest,
  assetUrl,
  type CharacterManifest,
  type CharacterManifestEntry,
} from '../../../game/characters/manifest';
import {
  CONFIG_COLUMN_SQL,
  SWITCH_FLAG_SQL,
  buildWorkingConfig,
  ensureAssetConfig,
  loadAllConfigRows,
  migrateLegacyRowIfNeeded,
  saveCharacterConfig,
  type ConfigRow,
} from './configIo';
import { FrameCanvas } from './FrameCanvas';
import { BoxTools } from './BoxTools';
import type { BoxKind, BoxSelection, EditorTool } from './types';

const deepClone = <T,>(v: T): T => JSON.parse(JSON.stringify(v)) as T;

export function CharacterConfigEditor() {
  // ------------------------------------------------------------ data
  const [manifest, setManifest] = useState<CharacterManifest | null>(null);
  const [fatalError, setFatalError] = useState<string | null>(null);
  const rowsRef = useRef<Map<string, ConfigRow>>(new Map());
  const [rowsLoaded, setRowsLoaded] = useState(false);
  const [configColumnMissing, setConfigColumnMissing] = useState(false);

  // ------------------------------------------------------------ selection
  const [selectedCharId, setSelectedCharId] = useState('');
  const [movement, setMovement] = useState('');
  const [assetIdx, setAssetIdx] = useState(0);
  const [direction, setDirection] = useState<string>('down');
  const [frameIdx, setFrameIdx] = useState(0);

  // ------------------------------------------------------------ editing
  const [working, setWorking] = useState<CharacterConfigV1 | null>(null);
  const [issues, setIssues] = useState<string[]>([]);
  const [dirty, setDirty] = useState(false);
  const [saving, setSaving] = useState(false);
  const [savedAt, setSavedAt] = useState<string | null>(null);
  const [saveErrors, setSaveErrors] = useState<string[]>([]);
  const [tool, setTool] = useState<EditorTool>('select');
  const [selection, setSelection] = useState<BoxSelection | null>(null);
  const [snap1px, setSnap1px] = useState(true);
  const [gridProblems, setGridProblems] = useState<string[]>([]);
  const [image, setImage] = useState<HTMLImageElement | null>(null);
  const [copied, setCopied] = useState(false);

  const workingRef = useRef<CharacterConfigV1 | null>(null);
  workingRef.current = working;

  // Every mutation bumps the sequence; a finished save only clears `dirty`
  // when nothing changed while its request was in flight.
  const mutationSeqRef = useRef(0);
  const saveChainRef = useRef<Promise<void>>(Promise.resolve());

  const markDirty = () => {
    mutationSeqRef.current += 1;
    setDirty(true);
  };

  // ------------------------------------------------------------ init
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const [mf, loaded] = await Promise.all([fetchCharacterManifest(), loadAllConfigRows()]);
        if (cancelled) return;
        const migrated = await migrateLegacyRowIfNeeded(
          loaded.rows,
          mf.characters.map((c) => c.id),
        );
        const finalLoaded = migrated ? await loadAllConfigRows() : loaded;
        if (cancelled) return;
        rowsRef.current = finalLoaded.rows;
        setConfigColumnMissing(finalLoaded.configColumnMissing);
        if (finalLoaded.loadError) setIssues((prev) => [...prev, `Erro ao carregar configs: ${finalLoaded.loadError}`]);
        setManifest(mf);
        setRowsLoaded(true);
        if (mf.characters.length > 0) setSelectedCharId(mf.characters[0].id);
      } catch (e) {
        if (!cancelled) setFatalError(e instanceof Error ? e.message : String(e));
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  const entry: CharacterManifestEntry | null = useMemo(
    () => manifest?.characters.find((c) => c.id === selectedCharId) ?? null,
    [manifest, selectedCharId],
  );

  // Rebuild the working copy when the character changes (not on every save)
  useEffect(() => {
    if (!entry || !rowsLoaded) return;
    const built = buildWorkingConfig(entry, rowsRef.current.get(entry.id));
    setWorking(built.config);
    setIssues(built.issues);
    setDirty(false);
    setSaveErrors([]);
    const movements = Object.keys(entry.movements);
    setMovement(movements.includes('walk') ? 'walk' : movements[0] ?? '');
    setAssetIdx(0);
    setDirection('down');
    setFrameIdx(0);
    setSelection(null);
    setTool('select');
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [entry?.id, rowsLoaded]);

  // ------------------------------------------------------------ asset
  const assets = entry?.movements[movement] ?? [];
  const asset = assets[assetIdx] ?? null;
  const assetKey = asset ? `${movement}/${asset.fileName}` : null;

  useEffect(() => {
    setImage(null);
    if (!asset) return;
    let stale = false;
    const img = new Image();
    img.src = assetUrl(asset);
    img.onload = () => {
      if (!stale) setImage(img);
    };
    return () => {
      stale = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [asset?.publicUrl]);

  // Create the per-asset grid entry on demand (auto-detection)
  useEffect(() => {
    if (!working || !asset || !assetKey || !entry) return;
    // Mid-switch renders: `working` may still belong to the PREVIOUS character
    // (the rebuild effect above runs first in the same flush). Grafting this
    // character's asset into it corrupts the other character's config with a
    // wrong grid — the "zoom" bug. Wait until the rebuild lands.
    if (working.characterId !== entry.id) return;
    if (working.assets[assetKey]) {
      setGridProblems([]);
      return;
    }
    const { config, problems } = ensureAssetConfig(working, assetKey, asset.width, asset.height);
    if (config !== working) {
      // Reference-checked update: if another setWorking landed meanwhile
      // (character switch), drop this stale ensure — the effect re-runs.
      setWorking((prev) => (prev === working ? config : prev));
      markDirty();
    }
    setGridProblems(problems);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [working, assetKey, asset, entry]);

  // Reset box selection when the visible frame changes
  useEffect(() => {
    setSelection(null);
  }, [assetKey, direction, frameIdx]);

  const assetCfg = working && assetKey ? working.assets[assetKey] : undefined;
  const directionOrder: readonly Direction8[] =
    assetCfg?.directionOrder ?? (entry ? directionRowsFor(entry.directions) : directionRowsFor(8));
  const rowIndex = Math.max(0, directionOrder.indexOf(direction as Direction8));
  const frameCount = assetCfg?.columns ?? 1;
  const clampedFrame = Math.min(frameIdx, frameCount - 1);
  const frameCfg: CombatFrameConfig =
    (assetCfg?.directions[direction]?.frames[String(clampedFrame)] as CombatFrameConfig | undefined) ??
    EMPTY_FRAME_CONFIG;

  const fw = assetCfg?.frameSize.width ?? 64;
  const fh = assetCfg?.frameSize.height ?? 64;
  const scale = Math.min(6, Math.max(1, Math.floor(420 / Math.max(fw, fh))));

  // ------------------------------------------------------------ mutation helpers
  const mutateFrame = (fn: (frame: CombatFrameConfig) => CombatFrameConfig) => {
    if (!assetKey) return;
    const dir = direction;
    const fi = String(clampedFrame);
    setWorking((prev) => {
      if (!prev) return prev;
      const aCfg = prev.assets[assetKey];
      if (!aCfg) return prev;
      const dirCfg = aCfg.directions[dir] ?? { frames: {} };
      const cur = (dirCfg.frames[fi] as CombatFrameConfig | undefined) ?? EMPTY_FRAME_CONFIG;
      const nextFrame = fn(deepClone(cur));
      return {
        ...prev,
        assets: {
          ...prev.assets,
          [assetKey]: {
            ...aCfg,
            directions: {
              ...aCfg.directions,
              [dir]: { frames: { ...dirCfg.frames, [fi]: nextFrame } },
            },
          },
        },
      };
    });
    markDirty();
  };

  const handleRectChange = (kind: BoxKind, index: number, rect: LocalRectangle) =>
    mutateFrame((f) => {
      if (f[kind].rectangles[index]) f[kind].rectangles[index] = rect;
      return f;
    });

  const handleRectAdd = (kind: BoxKind, rect: LocalRectangle) => {
    const newIndex = frameCfg[kind].rectangles.length;
    mutateFrame((f) => {
      f[kind].enabled = true;
      f[kind].rectangles.push(rect);
      return f;
    });
    setSelection({ kind, index: newIndex });
    setTool('select');
  };

  const handleDuplicate = () => {
    if (!selection) return;
    const src = frameCfg[selection.kind].rectangles[selection.index];
    if (!src) return;
    const newIndex = frameCfg[selection.kind].rectangles.length;
    mutateFrame((f) => {
      f[selection.kind].rectangles.push({ ...src, x: src.x + 4, y: src.y + 4 });
      return f;
    });
    setSelection({ kind: selection.kind, index: newIndex });
  };

  const handleDelete = () => {
    if (!selection) return;
    mutateFrame((f) => {
      f[selection.kind].rectangles.splice(selection.index, 1);
      return f;
    });
    setSelection(null);
  };

  const handleCopyFrom = (delta: -1 | 1) => {
    const srcIdx = clampedFrame + delta;
    if (srcIdx < 0 || srcIdx >= frameCount || !assetCfg) return;
    const src =
      (assetCfg.directions[direction]?.frames[String(srcIdx)] as CombatFrameConfig | undefined) ??
      EMPTY_FRAME_CONFIG;
    mutateFrame(() => deepClone(src));
  };

  const handleCopyHurtboxToDirection = () => {
    if (!assetKey || !assetCfg) return;
    const hurt = deepClone(frameCfg.hurtbox);
    const dir = direction;
    setWorking((prev) => {
      if (!prev) return prev;
      const aCfg = prev.assets[assetKey];
      if (!aCfg) return prev;
      const dirCfg = aCfg.directions[dir] ?? { frames: {} };
      const frames: Record<string, CombatFrameConfig> = { ...dirCfg.frames };
      for (let i = 0; i < aCfg.columns; i++) {
        const cur = (frames[String(i)] as CombatFrameConfig | undefined) ?? EMPTY_FRAME_CONFIG;
        frames[String(i)] = { ...deepClone(cur), hurtbox: deepClone(hurt) };
      }
      return {
        ...prev,
        assets: {
          ...prev.assets,
          [assetKey]: { ...aCfg, directions: { ...aCfg.directions, [dir]: { frames } } },
        },
      };
    });
    markDirty();
  };

  const handleClearFrame = () => {
    if (!window.confirm('Limpar todas as caixas deste frame?')) return;
    mutateFrame(() => deepClone(EMPTY_FRAME_CONFIG));
    setSelection(null);
  };

  const handleClearMovement = () => {
    if (!assetKey) return;
    if (!window.confirm(`Limpar TODAS as caixas de "${assetKey}" (todas as direções e frames)?`)) return;
    setWorking((prev) => {
      if (!prev) return prev;
      const aCfg = prev.assets[assetKey];
      if (!aCfg) return prev;
      return {
        ...prev,
        assets: { ...prev.assets, [assetKey]: { ...aCfg, directions: {} } },
      };
    });
    setSelection(null);
    markDirty();
  };

  const handleToggleGroup = (kind: BoxKind, enabled: boolean) =>
    mutateFrame((f) => {
      f[kind].enabled = enabled;
      return f;
    });

  // ------------------------------------------------------------ save
  // Saves are chained so they hit Supabase in order (an early save finishing
  // late can never overwrite a newer one), and `dirty` is only cleared when
  // the working copy didn't change while the request was in flight.
  const persist = (cfg: CharacterConfigV1) => {
    const seqAtSave = mutationSeqRef.current;
    const run = saveChainRef.current.then(async () => {
      setSaving(true);
      const res = await saveCharacterConfig(cfg);
      setSaving(false);
      if (res.configColumnMissing) setConfigColumnMissing(true);
      if (res.ok) {
        setSavedAt(new Date().toLocaleTimeString());
        if (mutationSeqRef.current === seqAtSave) setDirty(false);
        rowsRef.current.set(cfg.characterId, {
          character_id: cfg.characterId,
          origin_x: cfg.spriteOrigin.x,
          origin_y: cfg.spriteOrigin.y,
          body_offset_x: cfg.collisionBody.offsetX,
          body_offset_y: cfg.collisionBody.offsetY,
          body_radius: cfg.collisionBody.radius,
          config: deepClone(cfg),
        });
      } else if (res.error) {
        setSaveErrors([res.error]);
      }
    });
    saveChainRef.current = run.catch(() => {});
    return run;
  };

  const handleSave = async () => {
    if (!working) return;
    const v = validateCharacterConfig(working);
    if (!v.ok) {
      setSaveErrors(v.errors);
      return;
    }
    setSaveErrors([]);
    await persist(working);
  };

  // Origin/body: live update while dragging, auto-save on commit (mouseup /
  // numeric change) — preserves the old editor behavior.
  const handleOriginChange = (x: number, y: number, committed: boolean) => {
    setWorking((prev) => (prev ? { ...prev, spriteOrigin: { x, y } } : prev));
    markDirty();
    if (committed && workingRef.current) {
      void persist({ ...workingRef.current, spriteOrigin: { x, y } });
    }
  };

  const handleBodyChange = (offsetX: number, offsetY: number, committed: boolean, radius?: number) => {
    setWorking((prev) =>
      prev
        ? {
            ...prev,
            collisionBody: {
              ...prev.collisionBody,
              offsetX,
              offsetY,
              ...(radius !== undefined ? { radius } : {}),
            },
          }
        : prev,
    );
    markDirty();
    if (committed && workingRef.current) {
      const base = workingRef.current;
      void persist({
        ...base,
        collisionBody: {
          ...base.collisionBody,
          offsetX,
          offsetY,
          ...(radius !== undefined ? { radius } : {}),
        },
      });
    }
  };

  const applyManualGrid = (w: number, h: number, cols: number) => {
    if (!assetKey || w <= 0 || h <= 0 || cols < 1) return;
    setWorking((prev) => {
      if (!prev) return prev;
      const aCfg = prev.assets[assetKey];
      if (!aCfg) return prev;
      return {
        ...prev,
        assets: {
          ...prev.assets,
          [assetKey]: {
            ...aCfg,
            frameSize: { width: Math.floor(w), height: Math.floor(h) },
            columns: Math.floor(cols),
            manualGrid: true,
          },
        },
      };
    });
    markDirty();
    setGridProblems([]);
    setFrameIdx(0);
  };

  const copySql = async (sql: string) => {
    try {
      await navigator.clipboard.writeText(sql);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      window.prompt('Copie o SQL:', sql);
    }
  };

  // ------------------------------------------------------------ render
  if (fatalError) {
    return (
      <Shell>
        <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-6">
          <h2 className="text-red-400 font-semibold mb-2 flex items-center gap-2">
            <AlertTriangle size={16} /> Falha ao carregar o manifest de personagens
          </h2>
          <p className="text-sm text-red-300/80 font-mono">{fatalError}</p>
          <p className="text-xs text-slate-400 mt-3">
            Verifique se o servidor de desenvolvimento está rodando (o manifest é gerado pelo plugin Vite) e se a
            pasta public/assets/characters existe.
          </p>
        </div>
      </Shell>
    );
  }

  if (!manifest || !rowsLoaded) {
    return (
      <Shell>
        <p className="text-slate-400 text-sm">Carregando personagens…</p>
      </Shell>
    );
  }

  // Blocking manifest errors (e.g. duplicated character IDs)
  if (manifest.errors.length > 0) {
    return (
      <Shell>
        <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-6">
          <h2 className="text-red-400 font-semibold mb-3 flex items-center gap-2">
            <AlertTriangle size={16} /> Erros no manifest bloqueiam o editor
          </h2>
          <ul className="space-y-2">
            {manifest.errors.map((err, i) => (
              <li key={i} className="text-sm text-red-300/90">
                <span className="font-mono text-xs bg-red-500/10 px-1.5 py-0.5 rounded mr-2">{err.code}</span>
                {err.message}
                {err.paths && err.paths.length > 0 && (
                  <span className="block text-xs text-red-300/60 font-mono mt-0.5">{err.paths.join(' · ')}</span>
                )}
              </li>
            ))}
          </ul>
          <p className="text-xs text-slate-400 mt-4">
            Corrija as pastas em public/assets/characters e recarregue a página.
          </p>
        </div>
      </Shell>
    );
  }

  if (manifest.characters.length === 0) {
    return (
      <Shell>
        <p className="text-slate-400 text-sm">
          Nenhum personagem válido encontrado em public/assets/characters. Crie pastas no formato
          {' '}<code className="text-cyan-400">character NN - 4/8 directions</code>.
        </p>
      </Shell>
    );
  }

  const allWarnings = [...manifest.warnings, ...(entry?.warnings ?? []), ...issues];

  return (
    <Shell
      headerRight={
        <div className="flex items-center gap-3">
          {dirty && <span className="text-xs text-amber-400">alterações não salvas</span>}
          {savedAt && !dirty && <span className="text-xs text-emerald-400">salvo às {savedAt}</span>}
          <button
            onClick={handleSave}
            disabled={saving || !working}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-cyan-600 hover:bg-cyan-500 disabled:opacity-50 text-sm font-medium text-white transition-colors"
          >
            <Save size={14} /> {saving ? 'Salvando…' : 'Salvar'}
          </button>
        </div>
      }
    >
      {/* SQL banner: config column missing */}
      {configColumnMissing && (
        <div className="mb-6 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4">
          <div className="flex items-start gap-3">
            <AlertTriangle size={16} className="text-amber-400 mt-0.5 shrink-0" />
            <div className="flex-1 min-w-0">
              <p className="text-sm text-amber-300 font-medium mb-1">
                A coluna <code>config</code> (jsonb) não existe em <code>character_configs</code>.
              </p>
              <p className="text-xs text-amber-200/70 mb-2">
                Origem e corpo continuam salvando nas colunas antigas, mas as caixas de combate NÃO são persistidas
                até você rodar este SQL no Supabase (SQL Editor):
              </p>
              <div className="flex items-center gap-2">
                <code className="flex-1 text-xs bg-slate-950/60 border border-amber-500/20 rounded-md px-3 py-2 text-amber-100 font-mono overflow-x-auto whitespace-nowrap">
                  {CONFIG_COLUMN_SQL}
                </code>
                <button
                  onClick={() => copySql(`${CONFIG_COLUMN_SQL}\n${SWITCH_FLAG_SQL}`)}
                  className="flex items-center gap-1.5 px-3 py-2 rounded-md bg-amber-500/20 text-amber-300 hover:bg-amber-500/30 text-xs font-medium shrink-0"
                >
                  <Copy size={12} /> {copied ? 'Copiado!' : 'Copiar SQL'}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Warnings */}
      {allWarnings.length > 0 && (
        <div className="mb-6 rounded-xl border border-amber-500/20 bg-amber-500/5 px-4 py-3">
          <ul className="space-y-1">
            {allWarnings.map((w, i) => (
              <li key={i} className="text-xs text-amber-300/80">• {w}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Validation errors */}
      {saveErrors.length > 0 && (
        <div className="mb-6 rounded-xl border border-red-500/30 bg-red-500/10 px-4 py-3">
          <p className="text-sm text-red-400 font-medium mb-1">Não foi possível salvar:</p>
          <ul className="space-y-0.5 max-h-40 overflow-y-auto">
            {saveErrors.map((err, i) => (
              <li key={i} className="text-xs text-red-300/80 font-mono">• {err}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Character selector */}
      <div className="mb-6">
        <label className="text-xs text-slate-500 uppercase tracking-wide mb-2 block">Personagem</label>
        <div className="flex flex-wrap gap-2">
          {manifest.characters.map((c) => (
            <button
              key={c.id}
              onClick={() => setSelectedCharId(c.id)}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                selectedCharId === c.id ? 'bg-cyan-600 text-white' : 'bg-slate-800 text-slate-300 hover:bg-slate-700'
              }`}
            >
              {c.displayName}
              <span className={`ml-2 text-[10px] ${selectedCharId === c.id ? 'text-cyan-200' : 'text-slate-500'}`}>
                {c.directions} dir
              </span>
            </button>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-8">
        {/* -------------------------------------------------- left: canvas */}
        <div className="bg-slate-900 rounded-xl border border-slate-800 p-6">
          {/* Movement selector */}
          {entry && (
            <div className="mb-4">
              <label className="text-xs text-slate-500 uppercase tracking-wide mb-2 block">Movimento</label>
              <div className="flex flex-wrap gap-1">
                {Object.keys(entry.movements).map((m) => (
                  <button
                    key={m}
                    onClick={() => {
                      setMovement(m);
                      setAssetIdx(0);
                      setFrameIdx(0);
                    }}
                    className={`px-2 py-1 rounded text-xs font-medium transition-colors ${
                      movement === m ? 'bg-cyan-600 text-white' : 'bg-slate-800 text-slate-400 hover:bg-slate-700'
                    }`}
                  >
                    {m}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Per-movement damage settings (saved with Salvar) */}
          {working && assetKey && working.assets[assetKey] && (
            <div className="mb-4 flex flex-wrap items-center gap-4 rounded-lg bg-slate-800/60 border border-slate-700/60 px-3 py-2">
              <label className="flex items-center gap-2 text-xs text-slate-300 cursor-pointer">
                <input
                  type="checkbox"
                  checked={working.assets[assetKey].damageEnabled === true}
                  onChange={(e) => {
                    const on = e.target.checked;
                    setWorking((prev) => {
                      if (!prev || !assetKey) return prev;
                      const aCfg = prev.assets[assetKey];
                      if (!aCfg) return prev;
                      return {
                        ...prev,
                        assets: { ...prev.assets, [assetKey]: { ...aCfg, damageEnabled: on } },
                      };
                    });
                    markDirty();
                  }}
                  className="accent-red-500"
                />
                Dano ativo neste movimento
              </label>
              <label className="flex items-center gap-2 text-xs text-slate-400">
                Dano por acerto
                <input
                  type="number"
                  min={0}
                  max={1000}
                  value={working.assets[assetKey].damage ?? 10}
                  disabled={working.assets[assetKey].damageEnabled !== true}
                  onChange={(e) => {
                    const v = Math.max(0, Math.min(1000, Math.round(Number(e.target.value) || 0)));
                    setWorking((prev) => {
                      if (!prev || !assetKey) return prev;
                      const aCfg = prev.assets[assetKey];
                      if (!aCfg) return prev;
                      return {
                        ...prev,
                        assets: { ...prev.assets, [assetKey]: { ...aCfg, damage: v } },
                      };
                    });
                    markDirty();
                  }}
                  className="w-20 bg-slate-900 border border-slate-700 rounded px-2 py-1 text-xs text-white disabled:opacity-40"
                />
              </label>
              <span className="text-[10px] text-slate-500">
                Só causa dano com hitbox desenhada + "Ativas no jogo" ligado
              </span>
            </div>
          )}

          {/* PNG selector (only when the movement has multiple files) */}
          {assets.length > 1 && (
            <div className="mb-4">
              <label className="text-xs text-slate-500 uppercase tracking-wide mb-2 block">Arquivo</label>
              <div className="flex flex-wrap gap-1">
                {assets.map((a, i) => (
                  <button
                    key={a.fileName}
                    onClick={() => {
                      setAssetIdx(i);
                      setFrameIdx(0);
                    }}
                    className={`px-2 py-1 rounded text-xs font-mono transition-colors ${
                      assetIdx === i ? 'bg-cyan-600 text-white' : 'bg-slate-800 text-slate-400 hover:bg-slate-700'
                    }`}
                  >
                    {a.fileName}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Direction selector */}
          <div className="mb-4">
            <label className="text-xs text-slate-500 uppercase tracking-wide mb-2 block">Direção</label>
            <div className="flex flex-wrap gap-1">
              {directionOrder.map((dir) => (
                <button
                  key={dir}
                  onClick={() => {
                    setDirection(dir);
                    setFrameIdx(0);
                  }}
                  className={`px-2 py-1 rounded text-xs font-medium transition-colors ${
                    direction === dir ? 'bg-cyan-600 text-white' : 'bg-slate-800 text-slate-400 hover:bg-slate-700'
                  }`}
                >
                  {dir}
                </button>
              ))}
            </div>
          </div>

          {/* Frame slider */}
          <div className="mb-4">
            <label className="text-xs text-slate-500 uppercase tracking-wide mb-2 block">
              Frame ({clampedFrame + 1}/{frameCount})
            </label>
            <div className="flex items-center gap-3">
              <button
                onClick={() => setFrameIdx(Math.max(0, clampedFrame - 1))}
                disabled={clampedFrame === 0}
                className="px-2 py-1 rounded bg-slate-800 text-slate-300 hover:bg-slate-700 disabled:opacity-40 text-xs"
              >
                ←
              </button>
              <input
                type="range"
                min="0"
                max={Math.max(0, frameCount - 1)}
                value={clampedFrame}
                onChange={(e) => setFrameIdx(parseInt(e.target.value, 10))}
                className="flex-1 h-2 rounded-full appearance-none bg-slate-700 cursor-pointer
                  [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:w-4 [&::-webkit-slider-thumb]:h-4
                  [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-cyan-500
                  [&::-moz-range-thumb]:w-4 [&::-moz-range-thumb]:h-4
                  [&::-moz-range-thumb]:rounded-full [&::-moz-range-thumb]:bg-cyan-500
                  [&::-moz-range-thumb]:border-none"
              />
              <button
                onClick={() => setFrameIdx(Math.min(frameCount - 1, clampedFrame + 1))}
                disabled={clampedFrame >= frameCount - 1}
                className="px-2 py-1 rounded bg-slate-800 text-slate-300 hover:bg-slate-700 disabled:opacity-40 text-xs"
              >
                →
              </button>
            </div>
          </div>

          {/* Grid problems / manual override */}
          {(gridProblems.length > 0 || assetCfg?.manualGrid) && asset && assetCfg && (
            <ManualGridPanel
              problems={gridProblems}
              imageWidth={asset.width}
              imageHeight={asset.height}
              frameW={assetCfg.frameSize.width}
              frameH={assetCfg.frameSize.height}
              columns={assetCfg.columns}
              directions={working?.directions ?? 8}
              onApply={applyManualGrid}
            />
          )}

          {/* Canvas */}
          <div className="flex justify-center bg-slate-950 rounded-lg p-4 border border-slate-800 overflow-auto">
            {working && assetCfg ? (
              <FrameCanvas
                image={image}
                frameWidth={fw}
                frameHeight={fh}
                rowIndex={rowIndex}
                frameInDir={clampedFrame}
                scale={scale}
                origin={working.spriteOrigin}
                body={{
                  offsetX: working.collisionBody.offsetX,
                  offsetY: working.collisionBody.offsetY,
                  radius: working.collisionBody.radius,
                }}
                frame={frameCfg}
                showBoxes
                selection={selection}
                tool={tool}
                snap1px={snap1px}
                onOriginChange={handleOriginChange}
                onBodyChange={(x, y, committed) => handleBodyChange(x, y, committed)}
                onRectChange={handleRectChange}
                onRectAdd={handleRectAdd}
                onSelect={setSelection}
              />
            ) : (
              <p className="text-slate-500 text-sm py-16">Carregando frame…</p>
            )}
          </div>

          <div className="mt-3 flex flex-wrap items-center gap-4 text-xs text-slate-500">
            <span className="flex items-center gap-1">
              <span className="w-3 h-3 rounded-full border-2 border-cyan-400"></span> Origem (arraste)
            </span>
            <span className="flex items-center gap-1">
              <span className="w-3 h-3 rounded-full border-2 border-red-400"></span> Corpo (arraste)
            </span>
            <span className="flex items-center gap-1">
              <span className="w-3 h-3 border-2" style={{ borderColor: '#00ff66' }}></span> Hurtbox
            </span>
            <span className="flex items-center gap-1">
              <span className="w-3 h-3 border-2" style={{ borderColor: '#ff00ff' }}></span> Hitbox
            </span>
          </div>
        </div>

        {/* -------------------------------------------------- right: panels */}
        <div className="space-y-6">
          {/* Character attributes (HP) */}
          <div className="bg-slate-900 rounded-xl border border-slate-800 p-6">
            <div className="flex items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-emerald-500/10 flex items-center justify-center">
                  <span className="text-emerald-400 text-sm font-bold">HP</span>
                </div>
                <div>
                  <h2 className="text-sm font-medium text-white">Atributos</h2>
                  <p className="text-xs text-slate-400">Vida total do personagem (padrão 100)</p>
                </div>
              </div>
              <label className="flex items-center gap-2 text-xs text-slate-300">
                HP máximo
                <input
                  type="number"
                  min={1}
                  max={10000}
                  value={working?.maxHp ?? 100}
                  onChange={(e) => {
                    const v = Math.max(1, Math.min(10000, Math.round(Number(e.target.value) || 0)));
                    setWorking((prev) => (prev ? { ...prev, maxHp: v } : prev));
                    markDirty();
                  }}
                  className="w-24 bg-slate-800 border border-slate-700 rounded px-2 py-1 text-sm text-white text-right"
                />
              </label>
            </div>
          </div>

          {/* Combat boxes */}
          <div className="bg-slate-900 rounded-xl border border-slate-800 p-6">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-fuchsia-500/10 flex items-center justify-center">
                  <Swords className="w-4 h-4 text-fuchsia-400" />
                </div>
                <div>
                  <h2 className="text-sm font-medium text-white">Caixas de Combate</h2>
                  <p className="text-xs text-slate-400">Hurtbox (dano recebido) e hitbox (dano causado) por frame</p>
                </div>
              </div>
              <label className="flex items-center gap-2 text-xs text-slate-300 cursor-pointer">
                <input
                  type="checkbox"
                  checked={working?.combatBoxesEnabled ?? false}
                  onChange={(e) => {
                    setWorking((prev) => (prev ? { ...prev, combatBoxesEnabled: e.target.checked } : prev));
                    markDirty();
                  }}
                  className="accent-fuchsia-500"
                />
                Ativas no jogo
              </label>
            </div>

            <BoxTools
              frame={frameCfg}
              selection={selection}
              tool={tool}
              snap1px={snap1px}
              canCopyPrev={clampedFrame > 0}
              canCopyNext={clampedFrame < frameCount - 1}
              onToolChange={setTool}
              onSnapChange={setSnap1px}
              onToggleGroup={handleToggleGroup}
              onRectEdit={handleRectChange}
              onDuplicate={handleDuplicate}
              onDelete={handleDelete}
              onCopyFrom={handleCopyFrom}
              onCopyHurtboxToDirection={handleCopyHurtboxToDirection}
              onClearFrame={handleClearFrame}
              onClearMovement={handleClearMovement}
            />
          </div>

          {/* Origin */}
          <div className="bg-slate-900 rounded-xl border border-slate-800 p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-8 h-8 rounded-lg bg-cyan-500/10 flex items-center justify-center">
                <Crosshair className="w-4 h-4 text-cyan-400" />
              </div>
              <div>
                <h2 className="text-sm font-medium text-white">Origem do Sprite</h2>
                <p className="text-xs text-slate-400">Âncora do sprite (fração 0–1 do frame) — salva automaticamente</p>
              </div>
            </div>
            {working && (
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="text-xs text-slate-500 mb-1 block">X</label>
                  <input
                    type="number"
                    step="0.001"
                    min="0"
                    max="1"
                    value={working.spriteOrigin.x}
                    onChange={(e) => handleOriginChange(parseFloat(e.target.value) || 0, working.spriteOrigin.y, true)}
                    className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-white font-mono"
                  />
                </div>
                <div>
                  <label className="text-xs text-slate-500 mb-1 block">Y</label>
                  <input
                    type="number"
                    step="0.001"
                    min="0"
                    max="1"
                    value={working.spriteOrigin.y}
                    onChange={(e) => handleOriginChange(working.spriteOrigin.x, parseFloat(e.target.value) || 0, true)}
                    className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-white font-mono"
                  />
                </div>
              </div>
            )}
            <button
              onClick={() => handleOriginChange(0.5, 0.5, true)}
              className="mt-3 px-3 py-1.5 rounded-md text-xs font-medium bg-cyan-500/10 text-cyan-400 hover:bg-cyan-500/20 transition-colors"
            >
              Centralizar
            </button>
          </div>

          {/* Collision body */}
          <div className="bg-slate-900 rounded-xl border border-slate-800 p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-8 h-8 rounded-lg bg-red-500/10 flex items-center justify-center">
                <Circle className="w-4 h-4 text-red-400" />
              </div>
              <div>
                <h2 className="text-sm font-medium text-white">Corpo de Colisão</h2>
                <p className="text-xs text-slate-400">Círculo relativo à origem (px) — salvo automaticamente</p>
              </div>
            </div>
            {working && (
              <div className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="text-xs text-slate-500 mb-1 block">Offset X (px)</label>
                    <input
                      type="number"
                      step="0.5"
                      value={working.collisionBody.offsetX}
                      onChange={(e) =>
                        handleBodyChange(parseFloat(e.target.value) || 0, working.collisionBody.offsetY, true)
                      }
                      className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-white font-mono"
                    />
                  </div>
                  <div>
                    <label className="text-xs text-slate-500 mb-1 block">Offset Y (px)</label>
                    <input
                      type="number"
                      step="0.5"
                      value={working.collisionBody.offsetY}
                      onChange={(e) =>
                        handleBodyChange(working.collisionBody.offsetX, parseFloat(e.target.value) || 0, true)
                      }
                      className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-white font-mono"
                    />
                  </div>
                </div>
                <div>
                  <label className="text-xs text-slate-500 mb-1 block">Raio (px)</label>
                  <div className="flex items-center gap-3">
                    <input
                      type="range"
                      min="3"
                      max="30"
                      step="1"
                      value={working.collisionBody.radius}
                      onChange={(e) =>
                        handleBodyChange(
                          working.collisionBody.offsetX,
                          working.collisionBody.offsetY,
                          true,
                          parseFloat(e.target.value),
                        )
                      }
                      className="flex-1 h-2 rounded-full appearance-none bg-slate-700 cursor-pointer
                        [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:w-4 [&::-webkit-slider-thumb]:h-4
                        [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-red-500
                        [&::-moz-range-thumb]:w-4 [&::-moz-range-thumb]:h-4
                        [&::-moz-range-thumb]:rounded-full [&::-moz-range-thumb]:bg-red-500
                        [&::-moz-range-thumb]:border-none"
                    />
                    <span className="text-sm font-mono text-red-400 w-10 text-right">
                      {working.collisionBody.radius}px
                    </span>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Help */}
          <div className="bg-slate-900/50 rounded-xl border border-slate-800/50 p-5">
            <h3 className="text-xs font-medium text-slate-400 uppercase tracking-wide mb-2">Como funciona</h3>
            <ul className="text-xs text-slate-500 space-y-1.5">
              <li>- Arraste o <span className="text-cyan-400">crosshair ciano</span> para a origem (snap no centro)</li>
              <li>- Arraste o <span className="text-red-400">círculo vermelho</span> para o corpo de colisão</li>
              <li>- Use <span className="text-lime-400">+ Hurtbox</span> / <span className="text-fuchsia-400">+ Hitbox</span> e desenhe no frame; arraste para mover, use as alças para redimensionar</li>
              <li>- Origem/corpo salvam sozinhos; as caixas exigem o botão <span className="text-cyan-400">Salvar</span> (com validação)</li>
              <li>- No jogo (dev), tecle <span className="text-white font-mono">F</span> para atacar e ative o debug para ver as caixas ao vivo</li>
            </ul>
          </div>
        </div>
      </div>
    </Shell>
  );
}

// ---------------------------------------------------------------- shell

function Shell({ children, headerRight }: { children: React.ReactNode; headerRight?: React.ReactNode }) {
  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <div className="max-w-6xl mx-auto px-6 py-12">
        <div className="flex items-center justify-between gap-4 mb-10">
          <div className="flex items-center gap-4">
            <a
              href="/admin"
              className="flex items-center justify-center w-10 h-10 rounded-lg bg-slate-800 hover:bg-slate-700 transition-colors"
            >
              <ArrowLeft className="w-5 h-5 text-slate-300" />
            </a>
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-cyan-500/10 flex items-center justify-center">
                <Crosshair className="w-5 h-5 text-cyan-400" />
              </div>
              <div>
                <h1 className="text-xl font-semibold text-white">Editor de Personagens</h1>
                <p className="text-sm text-slate-400">
                  Origem, corpo de colisão e caixas de combate — personagens descobertos automaticamente
                </p>
              </div>
            </div>
          </div>
          {headerRight}
        </div>
        {children}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------- manual grid

function ManualGridPanel({
  problems,
  imageWidth,
  imageHeight,
  frameW,
  frameH,
  columns,
  directions,
  onApply,
}: {
  problems: string[];
  imageWidth: number;
  imageHeight: number;
  frameW: number;
  frameH: number;
  columns: number;
  directions: 4 | 8;
  onApply: (w: number, h: number, cols: number) => void;
}) {
  const [w, setW] = useState(frameW);
  const [h, setH] = useState(frameH);
  const [cols, setCols] = useState(columns);

  const retryAuto = () => {
    const det = detectGrid(imageWidth, imageHeight, directions);
    setW(det.frameWidth);
    setH(det.frameHeight);
    setCols(det.columns);
    if (det.ok) onApply(det.frameWidth, det.frameHeight, det.columns);
  };

  return (
    <div className="mb-4 rounded-lg border border-amber-500/30 bg-amber-500/5 p-3">
      <p className="text-xs text-amber-300 font-medium mb-1">Grade manual (detecção automática {problems.length > 0 ? 'falhou' : 'sobrescrita'})</p>
      {problems.length > 0 && (
        <ul className="mb-2">
          {problems.map((p, i) => (
            <li key={i} className="text-[11px] text-amber-200/70 font-mono">• {p}</li>
          ))}
        </ul>
      )}
      <p className="text-[11px] text-slate-400 mb-2 font-mono">
        Imagem: {imageWidth}×{imageHeight}px · linhas (direções): {directions}
      </p>
      <div className="flex items-end gap-2">
        <div>
          <label className="text-[10px] text-slate-500 block mb-0.5">Frame W</label>
          <input type="number" min={1} value={w} onChange={(e) => setW(parseInt(e.target.value, 10) || 1)}
            className="w-20 bg-slate-800 border border-slate-700 rounded-md px-2 py-1 text-xs text-white font-mono" />
        </div>
        <div>
          <label className="text-[10px] text-slate-500 block mb-0.5">Frame H</label>
          <input type="number" min={1} value={h} onChange={(e) => setH(parseInt(e.target.value, 10) || 1)}
            className="w-20 bg-slate-800 border border-slate-700 rounded-md px-2 py-1 text-xs text-white font-mono" />
        </div>
        <div>
          <label className="text-[10px] text-slate-500 block mb-0.5">Colunas</label>
          <input type="number" min={1} value={cols} onChange={(e) => setCols(parseInt(e.target.value, 10) || 1)}
            className="w-20 bg-slate-800 border border-slate-700 rounded-md px-2 py-1 text-xs text-white font-mono" />
        </div>
        <button onClick={() => onApply(w, h, cols)}
          className="px-3 py-1.5 rounded-md text-xs font-medium bg-amber-500/20 text-amber-300 hover:bg-amber-500/30">
          Aplicar
        </button>
        <button onClick={retryAuto}
          className="px-3 py-1.5 rounded-md text-xs font-medium bg-slate-800 text-slate-300 hover:bg-slate-700">
          Detectar de novo
        </button>
      </div>
    </div>
  );
}
